from pathlib import Path

try:
    Import("env")
    project_dir = Path(env.subst("$PROJECT_DIR"))
except NameError:
    project_dir = Path(__file__).resolve().parents[1]

source_files = [
    project_dir / "src" / "main.cpp",
    project_dir / "src" / "DiagnosticManager.h",
    project_dir / "src" / "DiagnosticManager.cpp",
    project_dir / "src" / "SdDataManager.h",
    project_dir / "src" / "SdDataManager.cpp",
]

destination_dir = project_dir / "arduino" / "WifiConnect"
destination = destination_dir / "WifiConnect.ino"

header = """// GENERATED FILE - DO NOT EDIT DIRECTLY
// Canonical source files:
//   src/main.cpp
//   src/DiagnosticManager.h
//   src/DiagnosticManager.cpp
//   src/SdDataManager.h
//   src/SdDataManager.cpp
// Generated by: tools/export_arduino.py
// PlatformIO Build/Upload regenerates this file automatically.

"""

destination_dir.mkdir(parents=True, exist_ok=True)

# Generate the Arduino sketch from main.cpp.
generated = header + source_files[0].read_text(encoding="utf-8")
existing = destination.read_text(encoding="utf-8") if destination.exists() else None

if existing != generated:
    destination.write_text(generated, encoding="utf-8", newline="\n")
    print("Generated Arduino compatibility sketch")
else:
    print("Arduino compatibility sketch is current")

# Copy the supporting source modules beside the generated sketch.
for source_file in source_files[1:]:
    destination_file = destination_dir / source_file.name
    source_text = source_file.read_text(encoding="utf-8")
    existing_text = destination_file.read_text(encoding="utf-8") if destination_file.exists() else None

    if existing_text != source_text:
        destination_file.write_text(source_text, encoding="utf-8", newline="\n")
        print(f"Generated Arduino compatibility file: {source_file.name}")
    else:
        print(f"Arduino compatibility file is current: {source_file.name}")