from pathlib import Path

try:
    Import("env")
    project_dir = Path(env.subst("$PROJECT_DIR"))
except NameError:
    project_dir = Path(__file__).resolve().parents[1]

source = project_dir / "src" / "main.cpp"
destination = project_dir / "arduino" / "WifiConnect" / "WifiConnect.ino"

header = """// GENERATED FILE - DO NOT EDIT DIRECTLY
// Canonical source: src/main.cpp
// Generated by: tools/export_arduino.py
// PlatformIO Build/Upload regenerates this file automatically.

"""

generated = header + source.read_text(encoding="utf-8")
existing = destination.read_text(encoding="utf-8") if destination.exists() else None

if existing != generated:
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(generated, encoding="utf-8", newline="\n")
    print("Generated Arduino compatibility sketch")
else:
    print("Arduino compatibility sketch is current")
