"""Build checks, host regression runner, and opt-in read-only device smoke checks."""
import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from urllib.parse import urlsplit
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
BUFFER_SIZES = (0, 1024, 2048, 8192, 16384, 32768)


def require(condition, message):
    if not condition:
        raise ValueError(message)


def check_source(root=ROOT):
    source = (root / 'src/main.cpp').read_text(encoding='utf-8')
    sketch = (root / 'arduino/WifiConnect/WifiConnect.ino').read_text(encoding='utf-8')
    header = ('// GENERATED FILE - DO NOT EDIT DIRECTLY\n'
              '// Canonical source: src/main.cpp\n'
              '// Generated by: tools/export_arduino.py\n'
              '// PlatformIO Build/Upload regenerates this file automatically.\n\n')
    require(sketch == header + source, 'Arduino sketch is stale; run python tools/export_arduino.py')
    start = source.index('String contextHelpScript()')
    context = source[start:source.index(')rawliteral";', start)]
    anchors = set(re.findall(r"\[\s*['\"]([a-z-]+)['\"]", context))
    sections = re.findall(r'^    "([a-z-]+)\|', source, re.M)
    require(len(sections) == len(set(sections)), 'Duplicate help section IDs')
    missing = anchors - set(sections) - {'serial-status-line'}
    require(not missing, 'Broken contextual help links: ' + ', '.join(sorted(missing)))
    require('R"LAYOUT(' in source and ')LAYOUT"' in source, 'Missing card layout script')
    print('PASS: generated sketch and contextual help destinations')


def check_status(status, expected_version=None):
    require(isinstance(status, dict), 'status.json is not an object')
    firmware, health, wifi = status['firmware'], status['systemHealth'], status['wifiSurvey']
    require(all(isinstance(part, dict) for part in (firmware, health, wifi)), 'Invalid status sections')
    require(isinstance(firmware.get('version'), str), 'Missing firmware version')
    if expected_version:
        require(firmware['version'].removeprefix('V') == expected_version.removeprefix('V'), 'Unexpected firmware version')
    for name in ('wifiHistoryBuffer', 'wifiHistoryIntegrity', 'bleHistoryBuffer', 'scanConfiguration'):
        require(health.get(name) == 'PASS', 'Device check failed: ' + name)
    require(health.get('overall') in ('PASS', 'WARN'), 'Overall device health failed')
    for used, capacity in (('observationsRetained', 'observationCapacity'), ('apTableUsed', 'apTableCapacity')):
        require(type(wifi.get(used)) is int and type(wifi.get(capacity)) is int, 'Invalid storage counters')
        require(0 <= wifi[used] <= wifi[capacity] and wifi[capacity] > 0, 'Invalid storage bounds: ' + used)
    require(wifi.get('historyIntegrityAnomalies') == 0, 'Wi-Fi history integrity anomalies')
    require(type(wifi.get('terminalBufferBytes')) is int and wifi['terminalBufferBytes'] in BUFFER_SIZES, 'Unsupported active terminal size')
    require(type(wifi.get('plotsEnabled')) is bool, 'Missing active plot setting')
    require(type(wifi.get('inventory')) is bool, 'Missing inventory mode flag')
    if wifi['inventory']:
        require(wifi.get('historicalMeasurements') == 0, 'Inventory unexpectedly has a measurement ring')
        require(wifi['observationsRetained'] == wifi['apTableUsed'], 'Inventory summary count mismatch')
    warnings = [key for key, value in health.items() if value == 'WARN']
    return warnings


def check_device(base, expected_version=None):
    parsed = urlsplit(base)
    require(parsed.scheme in ('http', 'https') and parsed.hostname and not parsed.username
            and not parsed.password and parsed.path in ('', '/') and not parsed.query and not parsed.fragment,
            'Use a device origin such as http://192.168.4.1 (no path or credentials)')
    base = base.rstrip('/')

    def get(path):
        with urlopen(base + path, timeout=30) as response:
            require(response.status == 200, 'HTTP failure: ' + path)
            data = response.read(2_000_001)
            require(len(data) <= 2_000_000, 'Response too large: ' + path)
            return data.decode('utf-8'), response.headers

    status = json.loads(get('/status.json')[0])
    warnings = check_status(status, expected_version)
    config = json.loads(get('/config.json')[0])
    require(type(config.get('terminalBufferBytes')) is int and config['terminalBufferBytes'] in BUFFER_SIZES,
            'Missing/invalid saved terminal size')
    require(type(config.get('plotsEnabled')) is bool, 'Missing saved plot setting')
    for path, marker in (('/settings', 'Developer Memory'), ('/help', 'developer-memory'),
                         ('/', 'esp32-card-layout-v1:'), ('/terminal', 'Active terminal capture:')):
        require(marker in get(path)[0], 'Missing deployed feature on ' + path)
    _, headers = get('/api/terminal?cursor=0&boot=0')
    require(int(headers.get('X-Terminal-Capacity', '-1')) == status['wifiSurvey']['terminalBufferBytes'],
            'Terminal capacity header disagrees with status')
    for name in ('terminalBufferBytes', 'plotsEnabled'):
        if config[name] != status['wifiSurvey'][name]:
            warnings.append(name + ': saved value differs from active value (restart pending or allocation failure)')
    print('PASS: deployed pages, configuration, terminal headers and storage integrity')
    for warning in warnings:
        print('WARN:', warning)
    return warnings


def run_host_tests():
    require(shutil.which('node'), 'Host suite needs Node.js on PATH')
    compiler = shutil.which('g++')
    use_wsl = os.name == 'nt' and not compiler and shutil.which('wsl')
    require(compiler or use_wsl, 'Host suite needs g++ (or WSL with python3 and g++ on Windows)')
    scripts = sorted((ROOT / 'Tools').glob('test_*.py')) + sorted((ROOT / 'Tools').glob('test_*.mjs'))
    failures = []
    for script in scripts:
        relative = script.relative_to(ROOT).as_posix()
        command = ['node', relative] if script.suffix == '.mjs' else (
            ['wsl', '--exec', 'python3', relative] if use_wsl else [sys.executable, relative])
        print('RUN:', relative, flush=True)
        try:
            result = subprocess.run(command, cwd=ROOT, timeout=180, check=False)
            if result.returncode:
                failures.append(relative)
        except (OSError, subprocess.TimeoutExpired) as error:
            print('FAIL:', error)
            failures.append(relative)
    require(not failures, 'Failed host tests: ' + ', '.join(failures))
    print(f'PASS: all {len(scripts)} host test scripts')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--host', action='store_true', help='Run every host regression test; requires Node.js and g++/WSL')
    parser.add_argument('--device', help='Opt-in device origin; GET-only smoke check (renews the Wi-Fi web hold)')
    parser.add_argument('--expect-version', help='Expected firmware version for --device')
    parser.add_argument('--strict', action='store_true', help='Fail device checks on WARN or pending settings')
    args = parser.parse_args()
    if (args.expect_version or args.strict) and not args.device:
        parser.error('--expect-version and --strict require --device')
    try:
        check_source()
        if args.host:
            run_host_tests()
        if args.device:
            warnings = check_device(args.device, args.expect_version)
            require(not args.strict or not warnings, 'Strict deployment check has warnings')
    except (ValueError, KeyError, TypeError, OSError) as error:
        print('FAIL:', error, file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
